# Generated by Django 3.2.9 on 2021-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Author', 'Auteur'), ('Contributor', 'Contributeur')], max_length=30, verbose_name='Rôle')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('desc', models.CharField(max_length=200)),
                ('tag', models.CharField(choices=[('Bug', 'Bug'), ('Improvement', 'Amélioration'), ('Task', 'Tâche')], max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Faible'), ('Medium', 'Moyenne'), ('High', 'Elevée')], max_length=30)),
                ('status', models.CharField(choices=[('To do', 'A faire'), ('In progress', 'En cours'), ('Finished', 'Terminé')], max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Problèmes recensés',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Back-end', 'Back-end'), ('Front-end', 'Front-end'), ('iOS', 'iOS'), ('Android', 'Android')], max_length=30)),
            ],
        ),
    ]
