# Generated by Django 3.2.9 on 2021-11-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Commentaire'},
        ),
        migrations.AlterModelOptions(
            name='contributors',
            options={'verbose_name': 'Contributeur'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'ordering': ['-created_time'], 'verbose_name': 'Problèmes recensé'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projet'},
        ),
    ]
